/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escritorio.frontend.rueda_calendarica;

import escritorio.backend.calendario_cholquij.fecha.ManejadorCalcular;
import escritorio.frontend.calendario_cholquij.fecha.CalcularFecha;
import static escritorio.frontend.linea_de_tiempo.LineaDeTiempo.BG;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelos.database.FechaHaabDb;
import modelos.database.Utilidades;
import modelos.objetos.FechaHaab;

/**
 *
 * @author sergio
 */
public class RuedaCalendarica extends javax.swing.JFrame {
public final static ImageIcon BG = new ImageIcon("Imagenes/BGRuedaCalendarica.jpg");
 FechaHaabDb acceso = new FechaHaabDb();
    /**
     * Creates new form RuedaCalendarica
     */
    public RuedaCalendarica() {
        initComponents();
        setBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreDia = new javax.swing.JLabel();
        lblNombreMes = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        lblDia = new javax.swing.JLabel();
        lblEnergia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblNahual = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setTitle("Rueda Calendarica");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel1.setText("Fecha:");

        jButton1.setBackground(new java.awt.Color(134, 134, 134));
        jButton1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setText("Calcular");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 155, 16));
        jLabel2.setText("Nahual");

        jLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 155, 16));
        jLabel3.setText("Energia");

        lblNombreDia.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        lblNombreDia.setForeground(new java.awt.Color(243, 155, 16));
        lblNombreDia.setText("Dia");

        lblNombreMes.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        lblNombreMes.setForeground(new java.awt.Color(243, 155, 16));
        lblNombreMes.setText("Mes");

        lblDia.setBackground(new java.awt.Color(134, 134, 134));
        lblDia.setForeground(new java.awt.Color(1, 1, 1));
        lblDia.setOpaque(true);
        lblDia.setPreferredSize(new java.awt.Dimension(102, 102));

        lblEnergia.setBackground(new java.awt.Color(134, 134, 134));
        lblEnergia.setForeground(new java.awt.Color(1, 1, 1));
        lblEnergia.setOpaque(true);
        lblEnergia.setPreferredSize(new java.awt.Dimension(102, 102));

        lblMes.setBackground(new java.awt.Color(134, 134, 134));
        lblMes.setForeground(new java.awt.Color(1, 1, 1));
        lblMes.setOpaque(true);
        lblMes.setPreferredSize(new java.awt.Dimension(102, 102));

        lblNahual.setBackground(new java.awt.Color(134, 134, 134));
        lblNahual.setForeground(new java.awt.Color(1, 1, 1));
        lblNahual.setOpaque(true);
        lblNahual.setPreferredSize(new java.awt.Dimension(102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(lblNombreDia))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(lblNahual, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombreMes)
                            .addComponent(lblDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNombreDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNahual, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblNombreMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManejadorCalcular manejadorCalcular = ManejadorCalcular.getInstancia();
//        System.out.println("DATE " + date.getCalendar().getTime());
        lblNahual.setIcon(manejadorCalcular.getIcon(CalcularFecha.nahual(CalcularFecha.timeCholqij(date.getCalendar().getTime().getTime()))));
        lblEnergia.setIcon(manejadorCalcular.getIconLvl(CalcularFecha.nivel(CalcularFecha.timeCholqij(date.getCalendar().getTime().getTime()))));
        
        FechaHaab fechaActual = acceso.getFechaEspecifica(Utilidades.DateToLocalDate(date.getDate()));
        lblNombreDia.setText("Dia - "+fechaActual.getNahual().getNombre());
        
        lblNombreMes.setText("Mes - "+fechaActual.getWinal().getNombre());
        fechaActual.getNahual().getImagen().colocarImagen(lblDia);
        fechaActual.getWinal().getImagen().colocarImagen(lblMes);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

        private void setBackground() {

        JLabel backgroundLbl = new JLabel();
        backgroundLbl.setSize(1050, 470);
        backgroundLbl.setLocation(-150, 0);
        backgroundLbl.setIcon(BG);
        this.add(backgroundLbl);
        backgroundLbl.setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEnergia;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNahual;
    private javax.swing.JLabel lblNombreDia;
    private javax.swing.JLabel lblNombreMes;
    // End of variables declaration//GEN-END:variables
}
